skip_vim_plugin "command_t"
skip_vim_plugin "color-sampler"
skip_vim_plugin "cucumber"
skip_vim_plugin "scala"
skip_vim_plugin "gist-vim"
skip_vim_plugin "puppet"
skip_vim_plugin "arduino"
skip_vim_plugin "nerdtree"
#skip_vim_plugin "nerdcommenter"
vim_plugin_task "vim-easymotion", "git://github.com/Lokaltog/vim-easymotion.git"
vim_plugin_task "html5", "git://github.com/othree/html5.vim.git"
vim_plugin_task "html5-syntax", "git://github.com/othree/html5-syntax.vim.git"
vim_plugin_task "tabular", "git://github.com/godlygeek/tabular.git"
vim_plugin_task "autoclose",        "https://github.com/Townk/vim-autoclose.git"
vim_plugin_task "coffeeScript-VIM-Snippets", "git://github.com/carlosvillu/coffeScript-VIM-Snippets.git"
vim_plugin_task "vim-ragtag",     "https://github.com/tpope/vim-ragtag.git"
#vim_plugin_task "vim-preview",    "https://github.com/greyblake/vim-preview.git"
#vim_plugin_task "zencoding-vim",    "https://github.com/mattn/zencoding-vim.git"
#vim_plugin_task "tcomment_vim",    "https://github.com/tomtom/tcomment_vim.git"
